import 'package:taskquest/features/games/models/game_models.dart';

class GameContentService {
  Future<List<GameQuestion>> fetchContent(GameSessionConfig config) async {
    // In a real app, this would check local cache, then Firebase.
    await Future.delayed(const Duration(seconds: 1)); // Simulate network

    List<GameQuestion> questions;
    switch (config.type) {
      case GameType.quiz:
        questions = _fetchQuizQuestions(config);
        break;
      case GameType.codeBlocks:
        questions = _fetchCodeBlocks(config);
        break;
      case GameType.sdlc:
        questions = _fetchSdlcSequences(config);
        break;
      case GameType.algorithm:
        questions = _fetchAlgorithmProblems(config);
        break;
    }

    // Shuffle and take 10
    questions.shuffle();
    return questions.take(10).toList();
  }

  List<QuizQuestion> _fetchQuizQuestions(GameSessionConfig config) {
    final difficulty = config.options['Difficulty'] ?? 
                      (config.options['Language Pool'] == 'Beginner Set' ? 'Beginner' : 'Intermediate');

    if (difficulty == 'Beginner') {
      return [
        QuizQuestion(
          id: 'q_beg_1',
          instruction: 'BASIC SYNTAX',
          explanation: 'The print() function is used to output text to the console in Python.',
          codeSnippet: 'Which keyword is used to print text in Python?',
          correctAnswer: 'print',
          options: ['echo', 'print', 'printf', 'System.out.println'],
          xpReward: 10,
        ),
        QuizQuestion(
          id: 'q_beg_2',
          instruction: 'COMMENTS',
          explanation: 'In Java, C++, and JavaScript, // is used for single-line comments.',
          codeSnippet: 'What symbol starts a single-line comment in Java?',
          correctAnswer: '//',
          options: ['#', '//', '/*', '--'],
          xpReward: 10,
        ),
        QuizQuestion(
          id: 'q_beg_3',
          instruction: 'HTML TAGS',
          explanation: '<h1> is the largest heading tag in HTML.',
          codeSnippet: 'Which HTML tag is used for the largest heading?',
          correctAnswer: '<h1>',
          options: ['<h6>', '<head>', '<h1>', '<header>'],
          xpReward: 10,
        ),
        QuizQuestion(
          id: 'q_beg_4',
          instruction: 'CSS BASICS',
          explanation: 'CSS stands for Cascading Style Sheets.',
          codeSnippet: 'What does CSS stand for?',
          correctAnswer: 'Cascading Style Sheets',
          options: ['Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style System', 'Colorful Style Sheets'],
          xpReward: 10,
        ),
        QuizQuestion(
          id: 'q_beg_5',
          instruction: 'VARIABLES',
          explanation: 'In modern JavaScript, "let" and "const" are preferred for variable declaration.',
          codeSnippet: 'Which keyword is used to declare a variable in JavaScript?',
          correctAnswer: 'let',
          options: ['var', 'let', 'const', 'All of these'],
          xpReward: 10,
        ),
        QuizQuestion(
          id: 'q_beg_6',
          instruction: 'FILE EXTENSIONS',
          explanation: '.py is the standard extension for Python source files.',
          codeSnippet: 'What is the file extension for Python files?',
          correctAnswer: '.py',
          options: ['.pt', '.py', '.python', '.pyt'],
          xpReward: 10,
        ),
        QuizQuestion(
          id: 'q_beg_7',
          instruction: 'ANDROID DEV',
          explanation: 'Kotlin is the modern, recommended language for Android app development.',
          codeSnippet: 'Which language is primarily recommended for Android development?',
          correctAnswer: 'Kotlin',
          options: ['Java', 'Swift', 'Kotlin', 'Objective-C'],
          xpReward: 10,
        ),
        QuizQuestion(
          id: 'q_beg_8',
          instruction: 'PYTHON FUNCTIONS',
          explanation: 'Python uses the "def" keyword to define functions.',
          codeSnippet: 'Which keyword is used to define a function in Python?',
          correctAnswer: 'def',
          options: ['function', 'def', 'func', 'define'],
          xpReward: 10,
        ),
        QuizQuestion(
          id: 'q_beg_9',
          instruction: 'SQL BASICS',
          explanation: 'SQL stands for Structured Query Language.',
          codeSnippet: 'What does SQL stand for?',
          correctAnswer: 'Structured Query Language',
          options: ['Simple Query Language', 'Structured Query Language', 'Sequential Query List', 'Standard Query Logic'],
          xpReward: 10,
        ),
        QuizQuestion(
          id: 'q_beg_10',
          instruction: 'CSS SELECTORS',
          explanation: 'The # symbol is used to target elements by their ID in CSS.',
          codeSnippet: 'Which symbol is used for IDs in CSS?',
          correctAnswer: '#',
          options: ['.', '#', '*', '@'],
          xpReward: 10,
        ),
        QuizQuestion(
          id: 'q_beg_11',
          instruction: 'WEB STRUCTURE',
          explanation: 'HTML provides the structure of a web page.',
          codeSnippet: 'Which language is used to structure web content?',
          correctAnswer: 'HTML',
          options: ['HTML', 'CSS', 'JS', 'PHP'],
          xpReward: 10,
        ),
      ];
    }

    if (difficulty == 'Advanced') {
      return [
        QuizQuestion(
          id: 'q_adv_1',
          instruction: 'RUST OWNERSHIP',
          explanation: 'Rust uses a unique ownership system to manage memory safely.',
          codeSnippet: 'Which language features an Ownership and Borrowing system for memory safety?',
          correctAnswer: 'Rust',
          options: ['C++', 'Rust', 'Go', 'Swift'],
          xpReward: 30,
        ),
        QuizQuestion(
          id: 'q_adv_2',
          instruction: 'JAVA VIRTUAL MACHINE',
          explanation: 'Java code is compiled into bytecode and run on the JVM.',
          codeSnippet: 'Which language is famous for the slogan "Write Once, Run Anywhere"?',
          correctAnswer: 'Java',
          options: ['Python', 'Java', 'C#', 'JavaScript'],
          xpReward: 25,
        ),
        QuizQuestion(
          id: 'q_adv_3',
          instruction: 'HASKELL PARADIGM',
          explanation: 'Haskell is a purely functional programming language.',
          codeSnippet: 'Which of these is a purely functional programming language?',
          correctAnswer: 'Haskell',
          options: ['Python', 'Scala', 'Haskell', 'Lisp'],
          xpReward: 30,
        ),
        QuizQuestion(
          id: 'q_adv_4',
          instruction: 'C++ MULTIPLE INHERITANCE',
          explanation: 'C++ supports multiple inheritance, unlike Java or C#.',
          codeSnippet: 'Which of these languages supports multiple inheritance?',
          correctAnswer: 'C++',
          options: ['Java', 'C#', 'C++', 'Python'],
          xpReward: 25,
        ),
        QuizQuestion(
          id: 'q_adv_5',
          instruction: 'GO CONCURRENCY',
          explanation: 'Go uses goroutines and channels for efficient concurrency.',
          codeSnippet: 'Which language uses "Goroutines" for concurrency?',
          correctAnswer: 'Go',
          options: ['Go', 'Erlang', 'Rust', 'Dart'],
          xpReward: 25,
        ),
        QuizQuestion(
          id: 'q_adv_6',
          instruction: 'ELIXIR BEAM',
          explanation: 'Elixir runs on the Erlang Virtual Machine (BEAM).',
          codeSnippet: 'Which language runs on the BEAM virtual machine?',
          correctAnswer: 'Elixir',
          options: ['Elixir', 'Ruby', 'Clojure', 'Haskell'],
          xpReward: 30,
        ),
        QuizQuestion(
          id: 'q_adv_7',
          instruction: 'SWIFT OPTIONALS',
          explanation: 'Swift uses Optionals (?) to handle the absence of a value.',
          codeSnippet: 'Which language introduced the concept of "Optional" types with ? syntax?',
          correctAnswer: 'Swift',
          options: ['Kotlin', 'Swift', 'C#', 'Dart'],
          xpReward: 25,
        ),
        QuizQuestion(
          id: 'q_adv_8',
          instruction: 'LISP SYNTAX',
          explanation: 'Lisp is known for its heavy use of parentheses.',
          codeSnippet: 'Which language family is known for "Lots of Irritating Superfluous Parentheses"?',
          correctAnswer: 'Lisp',
          options: ['Scheme', 'Lisp', 'Clojure', 'All of these'],
          xpReward: 30,
        ),
        QuizQuestion(
          id: 'q_adv_9',
          instruction: 'FORTRAN HISTORY',
          explanation: 'Fortran (Formula Translation) was one of the first high-level languages.',
          codeSnippet: 'Which language was the first high-level programming language, designed for scientific computing?',
          correctAnswer: 'Fortran',
          options: ['COBOL', 'Fortran', 'ALGOL', 'BASIC'],
          xpReward: 30,
        ),
        QuizQuestion(
          id: 'q_adv_10',
          instruction: 'TYPESCRIPT SUPERSET',
          explanation: 'TypeScript is a strict syntactical superset of JavaScript.',
          codeSnippet: 'Which language is a typed superset of JavaScript developed by Microsoft?',
          correctAnswer: 'TypeScript',
          options: ['CoffeeScript', 'TypeScript', 'ActionScript', 'Dart'],
          xpReward: 20,
        ),
      ];
    }

    // Default: Intermediate
    return [
      QuizQuestion(
        id: 'q_rust',
        instruction: 'IDENTIFY THE LANGUAGE — SYNTAX CLUE',
        explanation: 'fn, let, i32 and println! are Rust hallmarks',
        codeSnippet: 'fn main() {\n    let x: i32 = 42;\n    println!("Value: {}", x);\n}',
        correctAnswer: 'Rust',
        options: ['C++', 'Go', 'Rust', 'Swift'],
        xpReward: 20,
      ),
      QuizQuestion(
        id: 'q_js',
        instruction: 'IDENTIFY THE LANGUAGE — SYNTAX CLUE',
        explanation: 'The arrow function syntax and console.log are standard JavaScript.',
        codeSnippet: 'const greet = (name) => {\n  console.log(`Hello, \${name}!`);\n};',
        correctAnswer: 'JavaScript',
        options: ['JavaScript', 'Java', 'Python', 'C#'],
        xpReward: 20,
      ),
      QuizQuestion(
        id: 'q_python',
        instruction: 'IDENTIFY THE LANGUAGE — SYNTAX CLUE',
        explanation: 'Indentation-based blocks and the "def" keyword are Python signatures.',
        codeSnippet: 'def welcome(name):\n    print(f"Welcome, {name}!")',
        correctAnswer: 'Python',
        options: ['Ruby', 'Python', 'Perl', 'PHP'],
        xpReward: 20,
      ),
      QuizQuestion(
        id: 'q_dart',
        instruction: 'IDENTIFY THE LANGUAGE — SYNTAX CLUE',
        explanation: 'The fat arrow syntax and main() entry point are common in Dart.',
        codeSnippet: 'void main() => print("Hello from Dart!");',
        correctAnswer: 'Dart',
        options: ['Java', 'Swift', 'Dart', 'Kotlin'],
        xpReward: 20,
      ),
      QuizQuestion(
        id: 'q_ruby',
        instruction: 'IDENTIFY THE LANGUAGE — SYNTAX CLUE',
        explanation: 'The "puts" command and lack of semicolons/braces are typical of Ruby.',
        codeSnippet: '3.times do\n  puts "Happy coding!"\nend',
        correctAnswer: 'Ruby',
        options: ['Ruby', 'Python', 'Lua', 'Shell'],
        xpReward: 20,
      ),
      QuizQuestion(
        id: 'q_swift',
        instruction: 'IDENTIFY THE LANGUAGE — SYNTAX CLUE',
        explanation: 'The "func" keyword and string interpolation with \\() are Swift hallmarks.',
        codeSnippet: 'func greet(name: String) {\n    print("Hello, \\(name)!")\n}',
        correctAnswer: 'Swift',
        options: ['Kotlin', 'Objective-C', 'Swift', 'C#'],
        xpReward: 20,
      ),
      QuizQuestion(
        id: 'q_kotlin',
        instruction: 'IDENTIFY THE LANGUAGE — SYNTAX CLUE',
        explanation: 'The "fun" keyword and property declaration syntax are characteristic of Kotlin.',
        codeSnippet: 'fun main() {\n    val name = "Kotlin"\n    println("Hello, \$name")\n}',
        correctAnswer: 'Kotlin',
        options: ['Java', 'Kotlin', 'Swift', 'Scala'],
        xpReward: 20,
      ),
      QuizQuestion(
        id: 'q_php',
        instruction: 'IDENTIFY THE LANGUAGE — SYNTAX CLUE',
        explanation: 'Variables starting with \$ and the "echo" command are PHP signatures.',
        codeSnippet: '<?php\n\$greeting = "Hello";\necho \$greeting . " World!";\n?>',
        correctAnswer: 'PHP',
        options: ['Perl', 'PHP', 'Ruby', 'Hack'],
        xpReward: 15,
      ),
      QuizQuestion(
        id: 'q_go_fact',
        instruction: 'IDENTIFY THE LANGUAGE — FACT',
        explanation: 'Go was created at Google to improve programming productivity.',
        codeSnippet: 'Created at Google by Rob Pike, Ken Thompson, and Robert Griesemer.',
        correctAnswer: 'Go',
        options: ['Carbon', 'Go', 'Dart', 'Kotlin'],
        xpReward: 20,
      ),
      QuizQuestion(
        id: 'q_java_fact',
        instruction: 'IDENTIFY THE LANGUAGE — FACT',
        explanation: 'Java was originally called Oak and developed at Sun Microsystems.',
        codeSnippet: 'This language was originally designed for interactive television but was too advanced for the industry.',
        correctAnswer: 'Java',
        options: ['JavaScript', 'Java', 'C#', 'PHP'],
        xpReward: 20,
      ),
    ];
  }

  List<GameQuestion> _fetchCodeBlocks(GameSessionConfig config) {
    final language = config.options['Language'] ?? 'Python';
    final difficulty = config.options['Difficulty'] ?? 'Beginner';
    
    if (language == 'JavaScript') {
      if (difficulty == 'Beginner') {
        return [
          CodeBlockPuzzle(
            id: 'cb_js_beg_1',
            instruction: 'LOG TO CONSOLE',
            explanation: 'console.log() is used to print output in JavaScript.',
            codeSegments: ['console.', 'slot', '("Hello World");'],
            availableBlocks: ['log', 'print', 'write', 'echo'],
            correctAnswers: {1: 'log'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_beg_2',
            instruction: 'DECLARE VARIABLE',
            explanation: '"const" declares a constant variable.',
            codeSegments: ['', 'slot', ' x = 5;'],
            availableBlocks: ['const', 'var', 'let', 'val'],
            correctAnswers: {1: 'const'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_beg_3',
            instruction: 'ARRAY ACCESS',
            explanation: 'Arrays use square brackets for indexing.',
            codeSegments: ['const arr = [1, 2, 3];\nconst x = arr', 'slot', '0', 'slot', ';'],
            availableBlocks: ['[', ']', '(', ')'],
            correctAnswers: {1: '[', 3: ']'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_beg_4',
            instruction: 'FUNCTION KEYWORD',
            explanation: '"function" is used to define a named function.',
            codeSegments: ['', 'slot', ' add(a, b) {\n  return a + b;\n}'],
            availableBlocks: ['function', 'func', 'def', 'fn'],
            correctAnswers: {1: 'function'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_beg_5',
            instruction: 'IF STATEMENT',
            explanation: 'If statements use parentheses for the condition.',
            codeSegments: ['', 'slot', ' (x > 0) {\n  console.log("Positive");\n}'],
            availableBlocks: ['if', 'when', 'for', 'while'],
            correctAnswers: {1: 'if'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_beg_6',
            instruction: 'STRICT EQUALITY',
            explanation: '=== checks for both value and type equality.',
            codeSegments: ['if (x ', 'slot', ' 10) {\n  // do something\n}'],
            availableBlocks: ['===', '=', '==', 'equals'],
            correctAnswers: {1: '==='},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_beg_7',
            instruction: 'ADD TO ARRAY',
            explanation: 'push() adds an element to the end of an array.',
            codeSegments: ['const arr = [1];\narr.', 'slot', '(2);'],
            availableBlocks: ['push', 'add', 'append', 'insert'],
            correctAnswers: {1: 'push'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_beg_8',
            instruction: 'MODULO',
            explanation: 'The % operator returns the remainder.',
            codeSegments: ['const isEven = x ', 'slot', ' 2 === 0;'],
            availableBlocks: ['%', '/', '&', 'mod'],
            correctAnswers: {1: '%'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_beg_9',
            instruction: 'BOOLEAN NOT',
            explanation: '! is the logical NOT operator.',
            codeSegments: ['if (', 'slot', 'isLogged) {\n  login();\n}'],
            availableBlocks: ['!', 'not', '~', '??'],
            correctAnswers: {1: '!'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_beg_10',
            instruction: 'OBJECT PROPERTY',
            explanation: 'Dot notation is used to access object properties.',
            codeSegments: ['const user = { id: 1 };\nconst id = user', 'slot', 'id;'],
            availableBlocks: ['.', ':', '->', '#'],
            correctAnswers: {1: '.'},
            xpReward: 10,
          ),
        ];
      } else {
        return [
          CodeBlockPuzzle(
            id: 'cb_js_1',
            instruction: 'MAP THROUGH ARRAY',
            explanation: 'The map() method creates a new array with the results of calling a function for every array element.',
            codeSegments: ['const doubled = numbers.', 'slot', '((n) => ', 'slot', ' * 2);'],
            availableBlocks: ['map', 'filter', 'n', 'number'],
            correctAnswers: {1: 'map', 3: 'n'},
            xpReward: 20,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_2',
            instruction: 'ASYNC AWAIT',
            explanation: 'The "await" keyword is used inside an async function to wait for a Promise.',
            codeSegments: ['', 'slot', ' function fetch() {\n  const res = ', 'slot', ' getData();\n  return res;\n}'],
            availableBlocks: ['async', 'await', 'function', 'wait'],
            correctAnswers: {1: 'async', 3: 'await'},
            xpReward: 25,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_3',
            instruction: 'OBJECT DESTRUCTURING',
            explanation: 'Destructuring allows extracting multiple properties from an object into variables.',
            codeSegments: ['const user = { name: "Alice", age: 25 };\nconst ', 'slot', ' name, age ', 'slot', ' = user;'],
            availableBlocks: ['{', '}', '[', ']'],
            correctAnswers: {1: '{', 3: '}'},
            xpReward: 20,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_4',
            instruction: 'SPREAD OPERATOR',
            explanation: 'The spread operator (...) can be used to merge arrays.',
            codeSegments: ['const combined = [', 'slot', 'arr1, ', 'slot', 'arr2];'],
            availableBlocks: ['...', '..', '.', '*'],
            correctAnswers: {1: '...', 3: '...'},
            xpReward: 15,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_5',
            instruction: 'TEMPLATE LITERALS',
            explanation: 'Template literals use backticks and \${} for interpolation.',
            codeSegments: ['const msg = ', 'slot', 'Hello, ', 'slot', 'user}!', 'slot', ';'],
            availableBlocks: ['`', '\${', '}', '"'],
            correctAnswers: {1: '`', 3: '\${', 5: '`'},
            xpReward: 15,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_6',
            instruction: 'PROMISE ALL',
            explanation: 'Promise.all() waits for all promises in an array to resolve.',
            codeSegments: ['await ', 'slot', '.', 'slot', '([p1, p2, p3]);'],
            availableBlocks: ['Promise', 'all', 'race', 'Wait'],
            correctAnswers: {1: 'Promise', 3: 'all'},
            xpReward: 25,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_7',
            instruction: 'ARRAY FILTER',
            explanation: 'The filter() method creates a new array with elements that pass the test.',
            codeSegments: ['const evens = nums.', 'slot', '((n) => n ', 'slot', ' 2 === 0);'],
            availableBlocks: ['filter', '%', '/', 'find'],
            correctAnswers: {1: 'filter', 3: '%'},
            xpReward: 20,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_8',
            instruction: 'REDUCE ARRAY',
            explanation: 'The reduce() method executes a reducer function on each element of the array, resulting in a single output value.',
            codeSegments: ['const sum = nums.', 'slot', '((acc, n) => ', 'slot', ' + n, 0);'],
            availableBlocks: ['reduce', 'acc', 'total', 'sum'],
            correctAnswers: {1: 'reduce', 3: 'acc'},
            xpReward: 30,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_9',
            instruction: 'CLASS DECLARATION',
            explanation: 'Classes are a template for creating objects.',
            codeSegments: ['', 'slot', ' User ', 'slot', ' Entity {\n  constructor() { ', 'slot', '(); }\n}'],
            availableBlocks: ['class', 'extends', 'super', 'implements'],
            correctAnswers: {1: 'class', 3: 'extends', 5: 'super'},
            xpReward: 25,
          ),
          CodeBlockPuzzle(
            id: 'cb_js_10',
            instruction: 'TERNARY OPERATOR',
            explanation: 'The ternary operator is a shorthand for if-else.',
            codeSegments: ['const access = age >= 18 ', 'slot', ' "Yes" ', 'slot', ' "No";'],
            availableBlocks: ['?', ':', 'if', 'else'],
            correctAnswers: {1: '?', 3: ':'},
            xpReward: 15,
          ),
        ];
      }
    } else if (language == 'Java') {
      if (difficulty == 'Beginner') {
        return [
          CodeBlockPuzzle(
            id: 'cb_java_beg_1',
            instruction: 'PRINT LINE',
            explanation: 'System.out.println() prints to the console in Java.',
            codeSegments: ['System.out.', 'slot', '("Hello");'],
            availableBlocks: ['println', 'print', 'write', 'log'],
            correctAnswers: {1: 'println'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_beg_2',
            instruction: 'MAIN METHOD',
            explanation: 'The main method is the entry point of a Java program.',
            codeSegments: ['public static ', 'slot', ' main(String[] args) { }'],
            availableBlocks: ['void', 'int', 'String', 'main'],
            correctAnswers: {1: 'void'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_beg_3',
            instruction: 'INT VARIABLE',
            explanation: '"int" is used for integer variables.',
            codeSegments: ['', 'slot', ' score = 100;'],
            availableBlocks: ['int', 'Integer', 'number', 'var'],
            correctAnswers: {1: 'int'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_beg_4',
            instruction: 'NEW OBJECT',
            explanation: '"new" is used to instantiate a class.',
            codeSegments: ['Scanner sc = ', 'slot', ' Scanner(System.in);'],
            availableBlocks: ['new', 'create', 'make', 'build'],
            correctAnswers: {1: 'new'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_beg_5',
            instruction: 'BOOLEAN TYPE',
            explanation: '"boolean" stores true or false values.',
            codeSegments: ['', 'slot', ' isReady = true;'],
            availableBlocks: ['boolean', 'bool', 'bit', 'binary'],
            correctAnswers: {1: 'boolean'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_beg_6',
            instruction: 'FOR LOOP',
            explanation: 'For loops iterate a specific number of times.',
            codeSegments: ['', 'slot', ' (int i=0; i<10; i++) { }'],
            availableBlocks: ['for', 'while', 'each', 'loop'],
            correctAnswers: {1: 'for'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_beg_7',
            instruction: 'IF CONDITION',
            explanation: 'If statements execute code based on a condition.',
            codeSegments: ['', 'slot', ' (x == 10) { }'],
            availableBlocks: ['if', 'when', 'case', 'switch'],
            correctAnswers: {1: 'if'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_beg_8',
            instruction: 'CLASS KEYWORD',
            explanation: 'Classes are the building blocks of Java apps.',
            codeSegments: ['public ', 'slot', ' MyClass { }'],
            availableBlocks: ['class', 'object', 'struct', 'interface'],
            correctAnswers: {1: 'class'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_beg_9',
            instruction: 'RETURN VALUE',
            explanation: 'The return keyword exits a method and returns a value.',
            codeSegments: ['public int getVal() {\n  ', 'slot', ' 10;\n}'],
            availableBlocks: ['return', 'exit', 'give', 'result'],
            correctAnswers: {1: 'return'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_beg_10',
            instruction: 'STRING TYPE',
            explanation: '"String" (capital S) is used for text in Java.',
            codeSegments: ['', 'slot', ' name = "Java";'],
            availableBlocks: ['String', 'string', 'text', 'char[]'],
            correctAnswers: {1: 'String'},
            xpReward: 10,
          ),
        ];
      } else {
        return [
          CodeBlockPuzzle(
            id: 'cb_java_1',
            instruction: 'CLASS DECLARATION',
            explanation: 'In Java, the main method must be inside a public class.',
            codeSegments: ['public ', 'slot', ' Main {\n  public static ', 'slot', ' main(String[] args) {\n    System.out.', 'slot', '("Hello");\n  }\n}'],
            availableBlocks: ['class', 'void', 'println', 'log'],
            correctAnswers: {1: 'class', 3: 'void', 5: 'println'},
            xpReward: 20,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_2',
            instruction: 'INHERITANCE',
            explanation: 'In Java, a class inherits from another using the "extends" keyword.',
            codeSegments: ['class Dog ', 'slot', ' Animal ', 'slot', ' Mammal {\n  // methods\n}'],
            // Let's fix it
            availableBlocks: ['extends', 'implements'],
            correctAnswers: {1: 'extends'},
            xpReward: 20,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_3',
            instruction: 'ARRAYLIST INITIALIZATION',
            explanation: 'Generic types in Java are declared using angle brackets (< >).',
            codeSegments: ['List', 'slot', ' list = new ', 'slot', '<>();'],
            availableBlocks: ['<String>', 'ArrayList', 'LinkedList', 'List'],
            correctAnswers: {1: '<String>', 3: 'ArrayList'},
            xpReward: 25,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_4',
            instruction: 'EXCEPTION HANDLING',
            explanation: 'In Java, the try block is followed by a catch block to handle exceptions.',
            codeSegments: ['try {\n  int res = 10 / 0;\n} ', 'slot', ' (Exception e) {\n  System.out.println(e);\n} ', 'slot', ' {\n  // finally\n}'],
            availableBlocks: ['catch', 'finally', 'except', 'done'],
            correctAnswers: {1: 'catch', 3: 'finally'},
            xpReward: 25,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_5',
            instruction: 'INTERFACE IMPLEMENTATION',
            explanation: 'A class uses the "implements" keyword to use an interface.',
            codeSegments: ['class Circle ', 'slot', ' Shape, ', 'slot', ' {\n  public void draw() { }\n}'],
            availableBlocks: ['implements', 'Drawable', 'extends', 'Shape'],
            correctAnswers: {1: 'implements', 3: 'Drawable'},
            xpReward: 25,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_6',
            instruction: 'STATIC METHOD',
            explanation: 'Static methods can be called without creating an instance of the class.',
            codeSegments: ['public ', 'slot', ' ', 'slot', ' void printHeader() {\n  System.out.println("Header");\n}'],
            availableBlocks: ['static', 'final', 'public', 'private'],
            correctAnswers: {1: 'static'},
            xpReward: 15,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_7',
            instruction: 'STREAM API',
            explanation: 'Java Streams allow functional-style operations on collections.',
            codeSegments: ['list.stream().', 'slot', '(s -> s.startsWith("A")).', 'slot', '();'],
            availableBlocks: ['filter', 'collect', 'map', 'forEach'],
            correctAnswers: {1: 'filter', 3: 'collect'},
            xpReward: 30,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_8',
            instruction: 'LAMBDA EXPRESSION',
            explanation: 'Lambdas provide a clear and concise way to represent one method interface using an expression.',
            codeSegments: ['button.addActionListener(', 'slot', ' -> System.out.', 'slot', '("Clicked"));'],
            availableBlocks: ['e', 'println', 'event', 'log'],
            correctAnswers: {1: 'e', 3: 'println'},
            xpReward: 25,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_9',
            instruction: 'FOR-EACH LOOP',
            explanation: 'The enhanced for loop (for-each) uses a colon to iterate over a collection.',
            codeSegments: ['for (', 'slot', ' s ', 'slot', ' names) {\n  System.out.println(s);\n}'],
            availableBlocks: ['String', ':', 'in', 'of'],
            correctAnswers: {1: 'String', 3: ':'},
            xpReward: 15,
          ),
          CodeBlockPuzzle(
            id: 'cb_java_10',
            instruction: 'ABSTRACT CLASS',
            explanation: 'Abstract classes are declared with the "abstract" keyword and cannot be instantiated.',
            codeSegments: ['public ', 'slot', ' class Vehicle {\n  ', 'slot', ' void move();\n}'],
            availableBlocks: ['abstract', 'void', 'virtual', 'static'],
            correctAnswers: {1: 'abstract', 3: 'abstract'},
            xpReward: 25,
          ),
        ];
      }
    } else if (language == 'C++') {
      if (difficulty == 'Beginner') {
        return [
          CodeBlockPuzzle(
            id: 'cb_cpp_beg_1',
            instruction: 'OUTPUT TEXT',
            explanation: 'cout is used for output in C++.',
            codeSegments: ['std::', 'slot', ' << "Hello";'],
            availableBlocks: ['cout', 'cin', 'print', 'out'],
            correctAnswers: {1: 'cout'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_beg_2',
            instruction: 'INPUT TEXT',
            explanation: 'cin is used for input in C++.',
            codeSegments: ['std::', 'slot', ' >> x;'],
            availableBlocks: ['cin', 'cout', 'in', 'get'],
            correctAnswers: {1: 'cin'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_beg_3',
            instruction: 'INT MAIN',
            explanation: 'Every C++ program must have a main function.',
            codeSegments: ['int ', 'slot', '() { return 0; }'],
            availableBlocks: ['main', 'start', 'exec', 'run'],
            correctAnswers: {1: 'main'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_beg_4',
            instruction: 'INCLUDE HEADER',
            explanation: '#include is used to include library headers.',
            codeSegments: ['', 'slot', ' <iostream>'],
            availableBlocks: ['#include', '#import', 'using', 'require'],
            correctAnswers: {1: '#include'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_beg_5',
            instruction: 'END LINE',
            explanation: 'endl is used to start a new line and flush the buffer.',
            codeSegments: ['cout << "Hi" << std::', 'slot', ';'],
            availableBlocks: ['endl', 'nl', 'break', 'stop'],
            correctAnswers: {1: 'endl'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_beg_6',
            instruction: 'CONSTANT',
            explanation: 'const declares a variable that cannot be changed.',
            codeSegments: ['', 'slot', ' double PI = 3.14;'],
            availableBlocks: ['const', 'final', 'fixed', 'static'],
            correctAnswers: {1: 'const'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_beg_7',
            instruction: 'NAMESPACE',
            explanation: 'Namespaces prevent name collisions.',
            codeSegments: ['using ', 'slot', ' std;'],
            availableBlocks: ['namespace', 'package', 'module', 'lib'],
            correctAnswers: {1: 'namespace'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_beg_8',
            instruction: 'IF STATEMENT',
            explanation: 'If statements use curly braces for code blocks.',
            codeSegments: ['if (x > 0) ', 'slot', '\n  cout << "Pos";\n', 'slot', ''],
            availableBlocks: ['{', '}', '(', ')'],
            correctAnswers: {1: '{', 3: '}'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_beg_9',
            instruction: 'RETURN 0',
            explanation: 'Returning 0 from main indicates successful completion.',
            codeSegments: ['int main() {\n  ', 'slot', ' 0;\n}'],
            availableBlocks: ['return', 'exit', 'stop', 'done'],
            correctAnswers: {1: 'return'},
            xpReward: 10,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_beg_10',
            instruction: 'FOR LOOP',
            explanation: 'Standard for loop syntax.',
            codeSegments: ['for (int i=0; ', 'slot', ' < 5; i++) { }'],
            availableBlocks: ['i', 'x', '5', 'count'],
            correctAnswers: {1: 'i'},
            xpReward: 10,
          ),
        ];
      } else {
        return [
          CodeBlockPuzzle(
            id: 'cb_cpp_1',
            instruction: 'POINTER DECLARATION',
            explanation: 'In C++, an asterisk (*) is used to declare a pointer variable.',
            codeSegments: ['int val = 5;\nint', 'slot', ' ptr = ', 'slot', 'val;'],
            availableBlocks: ['*', '&', '**', 'ptr'],
            correctAnswers: {1: '*', 3: '&'},
            xpReward: 20,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_2',
            instruction: 'DYNAMIC ALLOCATION',
            explanation: 'new and delete manage heap memory.',
            codeSegments: ['int* p = ', 'slot', ' int[10];\n', 'slot', '[] p;'],
            availableBlocks: ['new', 'delete', 'malloc', 'free'],
            correctAnswers: {1: 'new', 3: 'delete'},
            xpReward: 25,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_3',
            instruction: 'CLASS MEMBER ACCESS',
            explanation: '-> is used to access members through a pointer.',
            codeSegments: ['User* u = new User();\nu', 'slot', 'setName("Bob");'],
            availableBlocks: ['->', '.', '::', '=>'],
            correctAnswers: {1: '->'},
            xpReward: 20,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_4',
            instruction: 'SCOPE RESOLUTION',
            explanation: ':: accesses members of a namespace or class.',
            codeSegments: ['std', 'slot', 'vector<int> v;\nMyClass', 'slot', 'staticMethod();'],
            availableBlocks: ['::', ':', '.', '->'],
            correctAnswers: {1: '::', 3: '::'},
            xpReward: 20,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_5',
            instruction: 'INITIALIZATION LIST',
            explanation: 'Constructors can use an initialization list to set member variables.',
            codeSegments: ['Point(int x, int y) ', 'slot', ' x(x), ', 'slot', '(y) { }'],
            availableBlocks: [':', 'y', '=', '{'],
            correctAnswers: {1: ':', 3: 'y'},
            xpReward: 25,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_6',
            instruction: 'VIRTUAL FUNCTIONS',
            explanation: 'The "virtual" keyword allows a function to be overridden in derived classes.',
            codeSegments: ['class Shape {\n  ', 'slot', ' void draw() ', 'slot', ' 0;\n};'],
            availableBlocks: ['virtual', '=', 'abstract', 'override'],
            correctAnswers: {1: 'virtual', 3: '='},
            xpReward: 25,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_7',
            instruction: 'SMART POINTERS',
            explanation: 'unique_ptr manages object lifetime automatically.',
            codeSegments: ['std::', 'slot', '<int> p = std::', 'slot', '<int>(10);'],
            availableBlocks: ['unique_ptr', 'make_unique', 'shared_ptr', 'make_shared'],
            correctAnswers: {1: 'unique_ptr', 3: 'make_unique'},
            xpReward: 30,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_8',
            instruction: 'REFERENCES',
            explanation: 'A reference is an alias for another variable, declared using &.',
            codeSegments: ['void swap(int', 'slot', ' a, int', 'slot', ' b) {\n  int t = a; a = b; b = t;\n}'],
            availableBlocks: ['&', '*', '&&', '@'],
            correctAnswers: {1: '&', 3: '&'},
            xpReward: 20,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_9',
            instruction: 'DESTRUCTOR',
            explanation: 'A destructor is called when an object is destroyed and starts with a tilde (~).',
            codeSegments: ['class List {\npublic:\n  ', 'slot', 'List() {\n    ', 'slot', '[] data;\n  }\n};'],
            availableBlocks: ['~', 'delete', '!', 'free'],
            correctAnswers: {1: '~', 3: 'delete'},
            xpReward: 25,
          ),
          CodeBlockPuzzle(
            id: 'cb_cpp_10',
            instruction: 'TEMPLATE CLASS',
            explanation: 'Templates allow classes to work with any data type.',
            codeSegments: ['', 'slot', ' <', 'slot', ' T>\nclass Box { T data; };'],
            availableBlocks: ['template', 'typename', 'class', 'type'],
            correctAnswers: {1: 'template', 3: 'typename'},
            xpReward: 30,
          ),
        ];
      }
    }

    // Default: Python
    if (difficulty == 'Beginner') {
      return [
        CodeBlockPuzzle(
          id: 'cb_py_beg_1',
          instruction: 'PRINT MESSAGE',
          explanation: 'print() outputs text in Python.',
          codeSegments: ['', 'slot', '("Hello")'],
          availableBlocks: ['print', 'log', 'echo', 'show'],
          correctAnswers: {1: 'print'},
          xpReward: 10,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_beg_2',
          instruction: 'VAR ASSIGNMENT',
          explanation: '= is used to assign values.',
          codeSegments: ['x ', 'slot', ' 10'],
          availableBlocks: ['=', '==', ':', 'set'],
          correctAnswers: {1: '='},
          xpReward: 10,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_beg_3',
          instruction: 'INPUT FUNCTION',
          explanation: 'input() reads text from the user.',
          codeSegments: ['name = ', 'slot', '("Enter name: ")'],
          availableBlocks: ['input', 'read', 'get', 'scan'],
          correctAnswers: {1: 'input'},
          xpReward: 10,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_beg_4',
          instruction: 'IF KEYWORD',
          explanation: 'if starts a conditional block.',
          codeSegments: ['', 'slot', ' x > 5:\n    print("Big")'],
          availableBlocks: ['if', 'when', 'for', 'while'],
          correctAnswers: {1: 'if'},
          xpReward: 10,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_beg_5',
          instruction: 'FOR LOOP',
          explanation: 'for loops use the "in" keyword.',
          codeSegments: ['for i ', 'slot', ' items:'],
          availableBlocks: ['in', 'of', 'at', 'through'],
          correctAnswers: {1: 'in'},
          xpReward: 10,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_beg_6',
          instruction: 'LIST DEFINITION',
          explanation: 'Lists use square brackets.',
          codeSegments: ['my_list = ', 'slot', '1, 2, 3', 'slot', ''],
          availableBlocks: ['[', ']', '(', ')'],
          correctAnswers: {1: '[', 3: ']'},
          xpReward: 10,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_beg_7',
          instruction: 'DEF KEYWORD',
          explanation: 'def starts a function definition.',
          codeSegments: ['', 'slot', ' my_func():'],
          availableBlocks: ['def', 'func', 'fn', 'function'],
          correctAnswers: {1: 'def'},
          xpReward: 10,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_beg_8',
          instruction: 'BOOLEAN TRUE',
          explanation: 'True is capitalized in Python.',
          codeSegments: ['is_active = ', 'slot', ''],
          availableBlocks: ['True', 'true', '1', 'YES'],
          correctAnswers: {1: 'True'},
          xpReward: 10,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_beg_9',
          instruction: 'INT CONVERSION',
          explanation: 'int() converts a string to an integer.',
          codeSegments: ['num = ', 'slot', '("123")'],
          availableBlocks: ['int', 'str', 'float', 'val'],
          correctAnswers: {1: 'int'},
          xpReward: 10,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_beg_10',
          instruction: 'WHILE LOOP',
          explanation: 'while loops continue while a condition is true.',
          codeSegments: ['', 'slot', ' count < 5:'],
          availableBlocks: ['while', 'until', 'for', 'during'],
          correctAnswers: {1: 'while'},
          xpReward: 10,
        ),
      ];
    } else {
      return [
        CodeBlockPuzzle(
          id: 'cb_py_1',
          instruction: 'COMPLETE THE LOOP',
          explanation: 'A for loop in Python uses the "in" keyword with range().',
          codeSegments: ['for i ', 'slot', ' ', 'slot', '(5):', '\n    print(i)'],
          availableBlocks: ['in', 'range', 'list', 'of'],
          correctAnswers: {1: 'in', 3: 'range'},
          xpReward: 20,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_2',
          instruction: 'LIST COMPREHENSION',
          explanation: 'List comprehensions provide a concise way to create lists.',
          codeSegments: ['squares = [x', 'slot', '2 for x ', 'slot', ' range(10)]'],
          availableBlocks: ['**', 'in', '*', 'of'],
          correctAnswers: {1: '**', 3: 'in'},
          xpReward: 25,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_3',
          instruction: 'FUNCTION DEFINITION',
          explanation: 'In Python, functions are defined using the "def" keyword.',
          codeSegments: ['', 'slot', ' calculate_total(items):\n    ', 'slot', ' sum(items)'],
          availableBlocks: ['def', 'return', 'func', 'result'],
          correctAnswers: {1: 'def', 3: 'return'},
          xpReward: 15,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_4',
          instruction: 'DICTIONARY ACCESS',
          explanation: 'Dictionaries in Python store data in key-value pairs.',
          codeSegments: ['user = {"name": "Bob", "id": 1}\nprint(user', 'slot', '"name"', 'slot', ')'],
          availableBlocks: ['[', ']', '(', ')'],
          correctAnswers: {1: '[', 3: ']'},
          xpReward: 15,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_5',
          instruction: 'IF-ELIF-ELSE',
          explanation: 'Python uses "elif" for else-if conditions.',
          codeSegments: ['if x > 10:\n    pass\n', 'slot', ' x > 5:\n    pass\n', 'slot', ':'],
          availableBlocks: ['elif', 'else', 'elseif', 'then'],
          correctAnswers: {1: 'elif', 3: 'else'},
          xpReward: 20,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_6',
          instruction: 'CLASS CONSTRUCTOR',
          explanation: 'The __init__ method is the constructor for a class in Python.',
          codeSegments: ['class Car:\n    def ', 'slot', '(', 'slot', ', brand):\n        self.brand = brand'],
          availableBlocks: ['__init__', 'self', '__new__', 'this'],
          correctAnswers: {1: '__init__', 3: 'self'},
          xpReward: 25,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_7',
          instruction: 'LIST SLICING',
          explanation: 'Slicing [start:stop] returns a portion of the list.',
          codeSegments: ['sub = my_list[', 'slot', ':', 'slot', ']'],
          availableBlocks: ['0', '5', '1', '10'],
          correctAnswers: {1: '0', 3: '5'},
          xpReward: 20,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_8',
          instruction: 'CONTEXT MANAGER',
          explanation: 'The "with" statement simplifies exception handling by encapsulating common preparation and cleanup tasks.',
          codeSegments: ['', 'slot', ' open("file.txt") ', 'slot', ' f:\n    data = f.read()'],
          availableBlocks: ['with', 'as', 'using', 'open'],
          correctAnswers: {1: 'with', 3: 'as'},
          xpReward: 25,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_9',
          instruction: 'LAMBDA FUNCTION',
          explanation: 'Lambda functions are small anonymous functions.',
          codeSegments: ['square = ', 'slot', ' x', 'slot', ' x * x'],
          availableBlocks: ['lambda', ':', 'func', '=>'],
          correctAnswers: {1: 'lambda', 3: ':'},
          xpReward: 25,
        ),
        CodeBlockPuzzle(
          id: 'cb_py_10',
          instruction: 'DECORATORS',
          explanation: 'Decorators are used to modify the behavior of a function or class.',
          codeSegments: ['', 'slot', 'login_required\ndef secret_page():\n    return "Secret"'],
          availableBlocks: ['@', '#', '\$', '%'],
          correctAnswers: {1: '@'},
          xpReward: 25,
        ),
      ];
    }
  }

  List<GameQuestion> _fetchSdlcSequences(GameSessionConfig config) {
    final difficulty = config.options['Difficulty'] ?? 'Normal';

    if (difficulty == 'Normal') {
      return [
        SdlcSequence(
          id: 'sdlc_norm_1',
          instruction: 'BASIC LOOP',
          explanation: 'The simplest development loop is Plan, Code, Test.',
          correctOrder: ['Plan', 'Code', 'Test'],
          shuffledPhases: ['Code', 'Test', 'Plan'],
          xpReward: 10,
        ),
        SdlcSequence(
          id: 'sdlc_norm_2',
          instruction: 'SIMPLE WATERFALL',
          explanation: 'Waterfall follows a linear sequence: Requirements, Design, Build.',
          correctOrder: ['Requirements', 'Design', 'Build'],
          shuffledPhases: ['Design', 'Build', 'Requirements'],
          xpReward: 10,
        ),
        SdlcSequence(
          id: 'sdlc_norm_3',
          instruction: 'RELEASE CYCLE',
          explanation: 'Code goes from Dev to Staging to Production.',
          correctOrder: ['Development', 'Staging', 'Production'],
          shuffledPhases: ['Production', 'Development', 'Staging'],
          xpReward: 10,
        ),
        SdlcSequence(
          id: 'sdlc_norm_4',
          instruction: 'BUG FIX',
          explanation: 'A bug is reported, fixed, and then verified.',
          correctOrder: ['Report', 'Fix', 'Verify'],
          shuffledPhases: ['Verify', 'Report', 'Fix'],
          xpReward: 10,
        ),
        SdlcSequence(
          id: 'sdlc_norm_5',
          instruction: 'TDD CORE',
          explanation: 'TDD follows Red, Green, Refactor.',
          correctOrder: ['Red (Fail)', 'Green (Pass)', 'Refactor'],
          shuffledPhases: ['Refactor', 'Green (Pass)', 'Red (Fail)'],
          xpReward: 15,
        ),
        SdlcSequence(
          id: 'sdlc_norm_6',
          instruction: 'FEATURE WORKFLOW',
          explanation: 'Branch, Code, Merge.',
          correctOrder: ['Create Branch', 'Code', 'Merge'],
          shuffledPhases: ['Merge', 'Create Branch', 'Code'],
          xpReward: 10,
        ),
        SdlcSequence(
          id: 'sdlc_norm_7',
          instruction: 'UI DESIGN',
          explanation: 'Sketch, Wireframe, Prototype.',
          correctOrder: ['Sketch', 'Wireframe', 'Prototype'],
          shuffledPhases: ['Prototype', 'Sketch', 'Wireframe'],
          xpReward: 10,
        ),
        SdlcSequence(
          id: 'sdlc_norm_8',
          instruction: 'STUDY SESSION',
          explanation: 'Read, Practice, Review.',
          correctOrder: ['Read', 'Practice', 'Review'],
          shuffledPhases: ['Review', 'Read', 'Practice'],
          xpReward: 10,
        ),
        SdlcSequence(
          id: 'sdlc_norm_9',
          instruction: 'SCRUM EVENT',
          explanation: 'Sprint Planning happens before the Sprint.',
          correctOrder: ['Planning', 'Sprint', 'Review'],
          shuffledPhases: ['Sprint', 'Review', 'Planning'],
          xpReward: 10,
        ),
        SdlcSequence(
          id: 'sdlc_norm_10',
          instruction: 'APP LAUNCH',
          explanation: 'Build, Beta Test, Launch.',
          correctOrder: ['Build', 'Beta Test', 'Launch'],
          shuffledPhases: ['Launch', 'Build', 'Beta Test'],
          xpReward: 10,
        ),
      ];
    }

    if (difficulty == 'Expert') {
      return [
        SdlcSequence(
          id: 'sdlc_exp_1',
          instruction: 'DEVSECOPS PIPELINE',
          explanation: 'Security is integrated at every step of the pipeline.',
          correctOrder: ['Plan', 'Code', 'Build', 'Security Scan', 'Test', 'Deploy', 'Monitor'],
          shuffledPhases: ['Security Scan', 'Monitor', 'Code', 'Test', 'Deploy', 'Plan', 'Build'],
          xpReward: 40,
        ),
        SdlcSequence(
          id: 'sdlc_exp_2',
          instruction: 'ENTERPRISE RELEASE',
          explanation: 'Complex releases involve multiple stakeholder and architecture checks.',
          correctOrder: ['Feasibility', 'Architecture', 'Development', 'QA', 'UAT', 'Production', 'Post-Mortem'],
          shuffledPhases: ['QA', 'Production', 'Feasibility', 'UAT', 'Architecture', 'Post-Mortem', 'Development'],
          xpReward: 45,
        ),
        SdlcSequence(
          id: 'sdlc_exp_3',
          instruction: 'SRE INCIDENT LOOP',
          explanation: 'SREs focus on reliability and learning from failures.',
          correctOrder: ['Alert', 'Triage', 'Mitigation', 'Resolution', 'Root Cause Analysis', 'Prevention Fix'],
          shuffledPhases: ['Mitigation', 'Prevention Fix', 'Alert', 'Resolution', 'Triage', 'Root Cause Analysis'],
          xpReward: 40,
        ),
        SdlcSequence(
          id: 'sdlc_exp_4',
          instruction: 'CI/CD ADVANCED',
          explanation: 'Modern pipelines include artifact storage and canary deployments.',
          correctOrder: ['Commit', 'Build', 'Unit Test', 'Store Artifact', 'Integration Test', 'Canary Deploy', 'Full Rollout'],
          shuffledPhases: ['Unit Test', 'Full Rollout', 'Commit', 'Canary Deploy', 'Build', 'Store Artifact', 'Integration Test'],
          xpReward: 50,
        ),
        SdlcSequence(
          id: 'sdlc_exp_5',
          instruction: 'V-MODEL (FULL)',
          explanation: 'The V-model maps development phases to verification phases.',
          correctOrder: ['Requirements', 'System Design', 'Architecture', 'Module Design', 'Unit Test', 'Integration Test', 'System Test'],
          shuffledPhases: ['Architecture', 'System Test', 'Requirements', 'Unit Test', 'System Design', 'Integration Test', 'Module Design'],
          xpReward: 50,
        ),
        SdlcSequence(
          id: 'sdlc_exp_6',
          instruction: 'MICROSERVICES DEPLOY',
          explanation: 'Service-oriented architectures require complex orchestration.',
          correctOrder: ['Service Build', 'Image Creation', 'Registry Push', 'Helm Chart Update', 'K8s Rollout', 'Health Check'],
          shuffledPhases: ['Helm Chart Update', 'Health Check', 'Service Build', 'K8s Rollout', 'Image Creation', 'Registry Push'],
          xpReward: 45,
        ),
        SdlcSequence(
          id: 'sdlc_exp_7',
          instruction: 'GIT FLOW (FULL)',
          explanation: 'Standard enterprise git workflow.',
          correctOrder: ['Feature Branch', 'Pull Request', 'Code Review', 'Approval', 'Merge to Develop', 'Release Branch', 'Merge to Main'],
          shuffledPhases: ['Approval', 'Merge to Main', 'Code Review', 'Release Branch', 'Feature Branch', 'Merge to Develop', 'Pull Request'],
          xpReward: 40,
        ),
        SdlcSequence(
          id: 'sdlc_exp_8',
          instruction: 'PRODUCT LIFECYCLE',
          explanation: 'From conception to retirement.',
          correctOrder: ['Discovery', 'MVP', 'Growth', 'Maturity', 'Saturation', 'Decline', 'End of Life'],
          shuffledPhases: ['Growth', 'End of Life', 'Discovery', 'Saturation', 'MVP', 'Decline', 'Maturity'],
          xpReward: 35,
        ),
        SdlcSequence(
          id: 'sdlc_exp_9',
          instruction: 'AGILE SCALE (SAFe)',
          explanation: 'Large-scale agile frameworks have multiple layers.',
          correctOrder: ['Portfolio Vision', 'Epic Refinement', 'Program Backlog', 'PI Planning', 'Iteration', 'Inspect & Adapt'],
          shuffledPhases: ['Iteration', 'Program Backlog', 'Portfolio Vision', 'Inspect & Adapt', 'Epic Refinement', 'PI Planning'],
          xpReward: 50,
        ),
        SdlcSequence(
          id: 'sdlc_exp_10',
          instruction: 'ISO 27001 AUDIT',
          explanation: 'Compliance cycles for security standards.',
          correctOrder: ['Gap Analysis', 'Risk Assessment', 'Implementation', 'Internal Audit', 'External Audit', 'Certification'],
          shuffledPhases: ['Risk Assessment', 'Certification', 'Gap Analysis', 'External Audit', 'Internal Audit', 'Implementation'],
          xpReward: 50,
        ),
      ];
    }

    // Default: Hard
    return [
      SdlcSequence(
        id: 'sdlc1',
        instruction: 'WATERFALL MODEL',
        explanation: 'The standard Waterfall model starts with Requirements and ends with Maintenance.',
        correctOrder: ['Requirements', 'Design', 'Implementation', 'Testing', 'Deployment', 'Maintenance'],
        shuffledPhases: ['Testing', 'Requirements', 'Maintenance', 'Design', 'Deployment', 'Implementation'],
        xpReward: 25,
      ),
      SdlcSequence(
        id: 'sdlc2',
        instruction: 'SCRUM CEREMONIES',
        explanation: 'A typical Scrum sprint starts with Planning and ends with a Retrospective.',
        correctOrder: ['Sprint Planning', 'Daily Standup', 'Sprint Review', 'Sprint Retrospective'],
        shuffledPhases: ['Daily Standup', 'Sprint Review', 'Sprint Retrospective', 'Sprint Planning'],
        xpReward: 20,
      ),
      SdlcSequence(
        id: 'sdlc3',
        instruction: 'BUG LIFECYCLE',
        explanation: 'A bug typically moves from New to Assigned, then Fixed, and finally Closed after verification.',
        correctOrder: ['New', 'Assigned', 'Fixed', 'Verified', 'Closed'],
        shuffledPhases: ['Fixed', 'Closed', 'Assigned', 'Verified', 'New'],
        xpReward: 20,
      ),
      SdlcSequence(
        id: 'sdlc4',
        instruction: 'AGILE SCRUM LIFECYCLE',
        explanation: 'Agile starts with a Vision and Product Backlog, then moves into Sprints.',
        correctOrder: ['Product Vision', 'Product Backlog', 'Sprint Backlog', 'Sprint', 'Shippable Product'],
        shuffledPhases: ['Sprint', 'Product Vision', 'Sprint Backlog', 'Shippable Product', 'Product Backlog'],
        xpReward: 30,
      ),
      SdlcSequence(
        id: 'sdlc5',
        instruction: 'CI/CD PIPELINE',
        explanation: 'A standard CI/CD pipeline starts with code commit and ends with monitoring.',
        correctOrder: ['Commit', 'Build', 'Test', 'Deploy', 'Monitor'],
        shuffledPhases: ['Test', 'Deploy', 'Build', 'Monitor', 'Commit'],
        xpReward: 25,
      ),
      SdlcSequence(
        id: 'sdlc6',
        instruction: 'GIT FEATURE WORKFLOW',
        explanation: 'A feature is developed on a branch, reviewed, and then merged.',
        correctOrder: ['Create Branch', 'Commit Changes', 'Pull Request', 'Code Review', 'Merge'],
        shuffledPhases: ['Merge', 'Pull Request', 'Commit Changes', 'Code Review', 'Create Branch'],
        xpReward: 20,
      ),
      SdlcSequence(
        id: 'sdlc7',
        instruction: 'TDD CYCLE',
        explanation: 'Test-Driven Development follows the Red-Green-Refactor pattern.',
        correctOrder: ['Write Test', 'Test Fails (Red)', 'Write Code', 'Test Passes (Green)', 'Refactor'],
        shuffledPhases: ['Refactor', 'Write Code', 'Test Passes (Green)', 'Write Test', 'Test Fails (Red)'],
        xpReward: 25,
      ),
      SdlcSequence(
        id: 'sdlc8',
        instruction: 'V-MODEL CORE',
        explanation: 'The V-Model emphasizes verification steps corresponding to development phases.',
        correctOrder: ['Requirements', 'System Design', 'Architecture', 'Module Design', 'Coding'],
        shuffledPhases: ['Coding', 'Architecture', 'Requirements', 'Module Design', 'System Design'],
        xpReward: 30,
      ),
      SdlcSequence(
        id: 'sdlc9',
        instruction: 'DEPLOYMENT STEPS',
        explanation: 'Deployment usually involves staging before production.',
        correctOrder: ['Build Artifact', 'Staging', 'UAT', 'Production', 'Sanity Check'],
        shuffledPhases: ['Production', 'Build Artifact', 'Staging', 'Sanity Check', 'UAT'],
        xpReward: 25,
      ),
      SdlcSequence(
        id: 'sdlc10',
        instruction: 'MOBILE RELEASE CYCLE',
        explanation: 'Mobile apps go through beta testing before store submission.',
        correctOrder: ['Development', 'Alpha Testing', 'Beta Testing', 'Store Submission', 'Approval'],
        shuffledPhases: ['Beta Testing', 'Approval', 'Development', 'Store Submission', 'Alpha Testing'],
        xpReward: 30,
      ),
    ];
  }

  List<GameQuestion> _fetchAlgorithmProblems(GameSessionConfig config) {
    final difficulty = config.options['Difficulty'] ?? 'Beginner';

    if (difficulty == 'Beginner') {
      return [
        AlgorithmProblem(
          id: 'algo_beg_basic_1',
          instruction: 'BASIC ARITHMETIC',
          explanation: '10 + 5 equals 15.',
          pseudocode: 'x = 10 + 5\nRETURN x',
          question: 'What is the value of x?',
          correctAnswer: '15',
          options: ['10', '15', '50', '5'],
          xpReward: 10,
        ),
        AlgorithmProblem(
          id: 'algo_beg_basic_2',
          instruction: 'BOOLEAN COMPARISON',
          explanation: '5 is greater than 2, so it returns True.',
          pseudocode: 'res = 5 > 2\nRETURN res',
          question: 'What is the value of res?',
          correctAnswer: 'True',
          options: ['True', 'False', 'None', 'Error'],
          xpReward: 10,
        ),
        AlgorithmProblem(
          id: 'algo_beg_basic_3',
          instruction: 'SIMPLE MULTIPLICATION',
          explanation: '2 multiplied by 3 is 6.',
          pseudocode: 'x = 2 * 3\nRETURN x',
          question: 'What is the value of x?',
          correctAnswer: '6',
          options: ['5', '6', '8', '9'],
          xpReward: 10,
        ),
        AlgorithmProblem(
          id: 'algo_beg_basic_4',
          instruction: 'DIVISION',
          explanation: '10 divided by 2 is 5.',
          pseudocode: 'x = 10 / 2\nRETURN x',
          question: 'What is the value of x?',
          correctAnswer: '5',
          options: ['2', '5', '10', '20'],
          xpReward: 10,
        ),
        AlgorithmProblem(
          id: 'algo_beg_basic_5',
          instruction: 'STRING CONCATENATION',
          explanation: 'Adding strings joins them together.',
          pseudocode: 's = "Hi" + "!"\nRETURN s',
          question: 'What is the value of s?',
          correctAnswer: 'Hi!',
          options: ['Hi!', 'Hi !', 'Hi', 'Error'],
          xpReward: 10,
        ),
        AlgorithmProblem(
          id: 'algo_beg_basic_6',
          instruction: 'EQUALITY CHECK',
          explanation: '7 is equal to 7, so it returns True.',
          pseudocode: 'res = (7 == 7)\nRETURN res',
          question: 'What is the value of res?',
          correctAnswer: 'True',
          options: ['True', 'False', '7', 'None'],
          xpReward: 10,
        ),
        AlgorithmProblem(
          id: 'algo_beg_basic_7',
          instruction: 'LOGICAL NOT',
          explanation: 'NOT True is False.',
          pseudocode: 'res = NOT True\nRETURN res',
          question: 'What is the value of res?',
          correctAnswer: 'False',
          options: ['True', 'False', 'None', 'Error'],
          xpReward: 10,
        ),
        AlgorithmProblem(
          id: 'algo_beg_basic_8',
          instruction: 'SUBTRACTION',
          explanation: '15 minus 5 is 10.',
          pseudocode: 'x = 15 - 5\nRETURN x',
          question: 'What is the value of x?',
          correctAnswer: '10',
          options: ['5', '10', '15', '20'],
          xpReward: 10,
        ),
        AlgorithmProblem(
          id: 'algo_beg_basic_9',
          instruction: 'MULTIPLY BY ZERO',
          explanation: 'Anything multiplied by 0 is 0.',
          pseudocode: 'x = 0 * 100\nRETURN x',
          question: 'What is the value of x?',
          correctAnswer: '0',
          options: ['0', '100', '1', 'Error'],
          xpReward: 10,
        ),
        AlgorithmProblem(
          id: 'algo_beg_basic_10',
          instruction: 'LESS THAN CHECK',
          explanation: '10 is not less than 1, so it returns False.',
          pseudocode: 'res = 10 < 1\nRETURN res',
          question: 'What is the value of res?',
          correctAnswer: 'False',
          options: ['True', 'False', '10', '1'],
          xpReward: 10,
        ),
      ];
    }

    if (difficulty == 'Intermediate') {
      return [
        AlgorithmProblem(
          id: 'algo_int_1',
          instruction: 'TRACE THE LOOP',
          explanation: 'The loop runs 3 times, adding i to x each time: 0+1+2 = 3.',
          pseudocode: 'x = 0\nFOR i FROM 0 TO 2:\n    x = x + i\nRETURN x',
          question: 'What is the final value of x?',
          correctAnswer: '3',
          options: ['0', '3', '6', '2'],
          xpReward: 20,
        ),
        AlgorithmProblem(
          id: 'algo_int_2',
          instruction: 'CONDITIONAL LOGIC',
          explanation: 'The condition (10 > 5) is true, so "YES" is returned.',
          pseudocode: 'FUNCTION check(n):\n    IF n > 5: RETURN "YES"\n    ELSE: RETURN "NO"',
          question: 'What does check(10) return?',
          correctAnswer: 'YES',
          options: ['YES', 'NO', 'TRUE', '10'],
          xpReward: 20,
        ),
        AlgorithmProblem(
          id: 'algo_int_3',
          instruction: 'STRING MANIPULATION',
          explanation: 'The loop iterates through the string and stops at the space.',
          pseudocode: 's = "DEV OPS"\nres = ""\nFOR char IN s:\n    IF char == " ": BREAK\n    res = res + char\nRETURN res',
          question: 'What is the final value of res?',
          correctAnswer: 'DEV',
          options: ['DEV', 'OPS', 'DEVOPS', 'D'],
          xpReward: 25,
        ),
        AlgorithmProblem(
          id: 'algo_int_4',
          instruction: 'MODULO OPERATOR',
          explanation: 'The modulo operator (%) returns the remainder of a division. 7 % 2 = 1.',
          pseudocode: 'x = 7 % 2\nRETURN x',
          question: 'What is the value of x?',
          correctAnswer: '1',
          options: ['0', '1', '3', '3.5'],
          xpReward: 15,
        ),
        AlgorithmProblem(
          id: 'algo_int_5',
          instruction: 'ARRAY INDEXING',
          explanation: 'Most programming languages use zero-based indexing. index 1 is the second element.',
          pseudocode: 'arr = [10, 20, 30]\nx = arr[1]\nRETURN x',
          question: 'What is the value of x?',
          correctAnswer: '20',
          options: ['10', '20', '30', '0'],
          xpReward: 15,
        ),
        AlgorithmProblem(
          id: 'algo_int_6',
          instruction: 'FIND MAXIMUM',
          explanation: 'The code compares each element to current max and updates if larger.',
          pseudocode: 'm = 0\nFOR x IN [1, 5, 2]:\n    IF x > m: m = x\nRETURN m',
          question: 'What is the value of m?',
          correctAnswer: '5',
          options: ['1', '5', '2', '0'],
          xpReward: 20,
        ),
        AlgorithmProblem(
          id: 'algo_int_7',
          instruction: 'BOOLEAN LOGIC',
          explanation: 'AND requires both conditions to be true. (5 > 2) is true, (3 > 10) is false.',
          pseudocode: 'res = (5 > 2) AND (3 > 10)\nRETURN res',
          question: 'What is the value of res?',
          correctAnswer: 'FALSE',
          options: ['TRUE', 'FALSE', 'NULL', 'ERROR'],
          xpReward: 15,
        ),
        AlgorithmProblem(
          id: 'algo_int_8',
          instruction: 'LIST LENGTH',
          explanation: 'The length of the list is the number of elements it contains.',
          pseudocode: 'arr = ["A", "B", "C", "D"]\nlen = arr.length\nRETURN len',
          question: 'What is the value of len?',
          correctAnswer: '4',
          options: ['3', '4', '5', '0'],
          xpReward: 15,
        ),
        AlgorithmProblem(
          id: 'algo_int_9',
          instruction: 'SIMPLE SUMMATION',
          explanation: 'The loop adds numbers 1 and 2 to total. 0 + 1 + 2 = 3.',
          pseudocode: 'total = 0\nFOR i FROM 1 TO 2:\n    total = total + i\nRETURN total',
          question: 'What is the value of total?',
          correctAnswer: '3',
          options: ['1', '2', '3', '0'],
          xpReward: 20,
        ),
        AlgorithmProblem(
          id: 'algo_int_10',
          instruction: 'VARIABLE SWAP',
          explanation: 'A temporary variable is used to swap values of a and b.',
          pseudocode: 'a = 5, b = 10\ntemp = a\na = b\nb = temp',
          question: 'What is the final value of b?',
          correctAnswer: '5',
          options: ['5', '10', '0', 'temp'],
          xpReward: 20,
        ),
      ];
    }

    if (difficulty == 'Advanced') {
      return [
        AlgorithmProblem(
          id: 'algo_adv_1',
          instruction: 'BINARY SEARCH TRACE',
          explanation: 'Binary search halves the search space each step. For 8 elements, it takes log2(8) = 3 steps max.',
          pseudocode: 'L = 0, R = 7\nWHILE L <= R:\n    M = (L + R) // 2\n    IF arr[M] == target: RETURN M\n    ELSE IF arr[M] < target: L = M + 1\n    ELSE: R = M - 1',
          question: 'In an array of 8 sorted items, what is the maximum number of comparisons?',
          correctAnswer: '3',
          options: ['8', '4', '3', '1'],
          xpReward: 50,
        ),
        AlgorithmProblem(
          id: 'algo_adv_2',
          instruction: 'RECURSION TRACE',
          explanation: 'fact(3) = 3 * fact(2) = 3 * 2 * fact(1) = 3 * 2 * 1 = 6.',
          pseudocode: 'FUNCTION fact(n):\n    IF n <= 1: RETURN 1\n    RETURN n * fact(n - 1)',
          question: 'What is the return value of fact(3)?',
          correctAnswer: '6',
          options: ['3', '6', '12', '24'],
          xpReward: 40,
        ),
        AlgorithmProblem(
          id: 'algo_adv_3',
          instruction: 'BIG O COMPLEXITY',
          explanation: 'Nested loops where both run up to N result in O(N^2) complexity.',
          pseudocode: 'FOR i FROM 0 TO N:\n    FOR j FROM 0 TO N:\n        print(i, j)',
          question: 'What is the time complexity of this algorithm?',
          correctAnswer: 'O(N^2)',
          options: ['O(N)', 'O(log N)', 'O(N^2)', 'O(1)'],
          xpReward: 45,
        ),
        AlgorithmProblem(
          id: 'algo_adv_4',
          instruction: 'BUBBLE SORT PASS',
          explanation: 'In one pass of bubble sort, the largest element "bubbles up" to the end.',
          pseudocode: 'arr = [5, 1, 4, 2, 8]\nFOR i FROM 0 TO 3:\n    IF arr[i] > arr[i+1]: SWAP(arr[i], arr[i+1])',
          question: 'What is the state of arr after ONE full pass?',
          correctAnswer: '[1, 4, 2, 5, 8]',
          options: ['[1, 4, 2, 5, 8]', '[5, 1, 4, 2, 8]', '[1, 2, 4, 5, 8]', '[8, 5, 4, 2, 1]'],
          xpReward: 40,
        ),
        AlgorithmProblem(
          id: 'algo_adv_5',
          instruction: 'LINKED LIST TRAVERSAL',
          explanation: 'Traversing to the end of a linked list with N nodes takes O(N) time.',
          pseudocode: 'curr = head\nWHILE curr.next IS NOT NULL:\n    curr = curr.next',
          question: 'What is the time complexity of finding the last element?',
          correctAnswer: 'O(N)',
          options: ['O(1)', 'O(log N)', 'O(N)', 'O(N^2)'],
          xpReward: 35,
        ),
        AlgorithmProblem(
          id: 'algo_adv_6',
          instruction: 'STACK OPERATIONS',
          explanation: 'Stacks are Last-In-First-Out (LIFO). 3 is pushed last, so it is popped first.',
          pseudocode: 'stack.push(1)\nstack.push(2)\nstack.push(3)\nx = stack.pop()\ny = stack.pop()',
          question: 'What is the value of y?',
          correctAnswer: '2',
          options: ['1', '2', '3', 'NULL'],
          xpReward: 30,
        ),
        AlgorithmProblem(
          id: 'algo_adv_7',
          instruction: 'QUEUE OPERATIONS',
          explanation: 'Queues are First-In-First-Out (FIFO). 1 is enqueued first, so it is dequeued first.',
          pseudocode: 'queue.enqueue(1)\nqueue.enqueue(2)\nqueue.enqueue(3)\nx = queue.dequeue()',
          question: 'What is the value of x?',
          correctAnswer: '1',
          options: ['1', '2', '3', '0'],
          xpReward: 30,
        ),
        AlgorithmProblem(
          id: 'algo_adv_8',
          instruction: 'MERGE SORT DIVIDE',
          explanation: 'Merge sort is a divide-and-conquer algorithm with O(N log N) complexity.',
          pseudocode: 'FUNCTION mergeSort(arr):\n    IF len(arr) <= 1: RETURN arr\n    mid = len(arr) // 2\n    L = mergeSort(arr[:mid])\n    R = mergeSort(arr[mid:])\n    RETURN merge(L, R)',
          question: 'What is the time complexity of Merge Sort?',
          correctAnswer: 'O(N log N)',
          options: ['O(N)', 'O(N^2)', 'O(N log N)', 'O(log N)'],
          xpReward: 50,
        ),
        AlgorithmProblem(
          id: 'algo_adv_9',
          instruction: 'HASH MAP SEARCH',
          explanation: 'Average case search in a Hash Map is O(1) if the hash function is good.',
          pseudocode: 'map.put("key", "value")\nval = map.get("key")',
          question: 'What is the average time complexity for searching a key?',
          correctAnswer: 'O(1)',
          options: ['O(1)', 'O(N)', 'O(log N)', 'O(N log N)'],
          xpReward: 40,
        ),
        AlgorithmProblem(
          id: 'algo_adv_10',
          instruction: 'TREE DEPTH SEARCH',
          explanation: 'DFS uses a stack (often via recursion) to explore as far as possible.',
          pseudocode: 'FUNCTION DFS(node):\n    IF node IS NULL: RETURN\n    print(node.val)\n    DFS(node.left)\n    DFS(node.right)',
          question: 'Which data structure is typically used for DFS?',
          correctAnswer: 'Stack',
          options: ['Queue', 'Stack', 'Heap', 'Linked List'],
          xpReward: 45,
        ),
      ];
    }

    // Default: Intermediate (Fallthrough for any other value)
    return [
      AlgorithmProblem(
        id: 'algo_int_1',
        instruction: 'TRACE THE LOOP',
        explanation: 'The loop runs 3 times, adding i to x each time: 0+1+2 = 3.',
        pseudocode: 'x = 0\nFOR i FROM 0 TO 2:\n    x = x + i\nRETURN x',
        question: 'What is the final value of x?',
        correctAnswer: '3',
        options: ['0', '3', '6', '2'],
        xpReward: 20,
      ),
      AlgorithmProblem(
        id: 'algo_int_2',
        instruction: 'CONDITIONAL LOGIC',
        explanation: 'The condition (10 > 5) is true, so "YES" is returned.',
        pseudocode: 'FUNCTION check(n):\n    IF n > 5: RETURN "YES"\n    ELSE: RETURN "NO"',
        question: 'What does check(10) return?',
        correctAnswer: 'YES',
        options: ['YES', 'NO', 'TRUE', '10'],
        xpReward: 20,
      ),
      AlgorithmProblem(
        id: 'algo_int_3',
        instruction: 'STRING MANIPULATION',
        explanation: 'The loop iterates through the string and stops at the space.',
        pseudocode: 's = "DEV OPS"\nres = ""\nFOR char IN s:\n    IF char == " ": BREAK\n    res = res + char\nRETURN res',
        question: 'What is the final value of res?',
        correctAnswer: 'DEV',
        options: ['DEV', 'OPS', 'DEVOPS', 'D'],
        xpReward: 25,
      ),
      AlgorithmProblem(
        id: 'algo_int_4',
        instruction: 'MODULO OPERATOR',
        explanation: 'The modulo operator (%) returns the remainder of a division. 7 % 2 = 1.',
        pseudocode: 'x = 7 % 2\nRETURN x',
        question: 'What is the value of x?',
        correctAnswer: '1',
        options: ['0', '1', '3', '3.5'],
        xpReward: 15,
      ),
      AlgorithmProblem(
        id: 'algo_int_5',
        instruction: 'ARRAY INDEXING',
        explanation: 'Most programming languages use zero-based indexing. index 1 is the second element.',
        pseudocode: 'arr = [10, 20, 30]\nx = arr[1]\nRETURN x',
        question: 'What is the value of x?',
        correctAnswer: '20',
        options: ['10', '20', '30', '0'],
        xpReward: 15,
      ),
      AlgorithmProblem(
        id: 'algo_int_6',
        instruction: 'FIND MAXIMUM',
        explanation: 'The code compares each element to current max and updates if larger.',
        pseudocode: 'm = 0\nFOR x IN [1, 5, 2]:\n    IF x > m: m = x\nRETURN m',
        question: 'What is the value of m?',
        correctAnswer: '5',
        options: ['1', '5', '2', '0'],
        xpReward: 20,
      ),
      AlgorithmProblem(
        id: 'algo_int_7',
        instruction: 'BOOLEAN LOGIC',
        explanation: 'AND requires both conditions to be true. (5 > 2) is true, (3 > 10) is false.',
        pseudocode: 'res = (5 > 2) AND (3 > 10)\nRETURN res',
        question: 'What is the value of res?',
        correctAnswer: 'FALSE',
        options: ['TRUE', 'FALSE', 'NULL', 'ERROR'],
        xpReward: 15,
      ),
      AlgorithmProblem(
        id: 'algo_int_8',
        instruction: 'LIST LENGTH',
        explanation: 'The length of the list is the number of elements it contains.',
        pseudocode: 'arr = ["A", "B", "C", "D"]\nlen = arr.length\nRETURN len',
        question: 'What is the value of len?',
        correctAnswer: '4',
        options: ['3', '4', '5', '0'],
        xpReward: 15,
      ),
      AlgorithmProblem(
        id: 'algo_int_9',
        instruction: 'SIMPLE SUMMATION',
        explanation: 'The loop adds numbers 1 and 2 to total. 0 + 1 + 2 = 3.',
        pseudocode: 'total = 0\nFOR i FROM 1 TO 2:\n    total = total + i\nRETURN total',
        question: 'What is the value of total?',
        correctAnswer: '3',
        options: ['1', '2', '3', '0'],
        xpReward: 20,
      ),
      AlgorithmProblem(
        id: 'algo_int_10',
        instruction: 'VARIABLE SWAP',
        explanation: 'A temporary variable is used to swap values of a and b.',
        pseudocode: 'a = 5, b = 10\ntemp = a\na = b\nb = temp',
        question: 'What is the final value of b?',
        correctAnswer: '5',
        options: ['5', '10', '0', 'temp'],
        xpReward: 20,
      ),
    ];
  }
}
