// Copyright (c) 2026 TaskQuest. All rights reserved.

import 'package:taskquest/features/games/models/game_models.dart';

final List<QuizQuestion> allQuizQuestions = [
  // Beginner
  QuizQuestion(
    id: 'q_lang_01',
    instruction: 'Which language is the primary foundation for React?',
    codeSnippet: 'const App = () => <h1>Hello World</h1>;',
    correctAnswer: 'JavaScript',
    options: ['Java', 'JavaScript', 'Python', 'C++'],
    explanation: 'React is a JavaScript library for building user interfaces.',
    xpReward: 10,
  ),
  QuizQuestion(
    id: 'q_lang_02',
    instruction: 'Which language uses indentation instead of curly braces for scoping?',
    codeSnippet: 'def hello():\n    print("Hello")',
    correctAnswer: 'Python',
    options: ['Python', 'Ruby', 'JavaScript', 'C#'],
    explanation: 'Python relies on strict indentation to define blocks of code.',
    xpReward: 10,
  ),
  QuizQuestion(
    id: 'q_lang_03',
    instruction: 'Which language is currently the preferred choice for native Android development?',
    codeSnippet: 'fun main() {\n    println("Hello Android")\n}',
    correctAnswer: 'Kotlin',
    options: ['Java', 'Swift', 'Kotlin', 'Dart'],
    explanation: 'Kotlin is the officially recommended language by Google for Android app development.',
    xpReward: 10,
  ),
  QuizQuestion(
    id: 'q_lang_04',
    instruction: 'Which language is used to style the visual presentation of web pages?',
    codeSnippet: 'body {\n    background-color: #fff;\n}',
    correctAnswer: 'CSS',
    options: ['HTML', 'JavaScript', 'CSS', 'XML'],
    explanation: 'Cascading Style Sheets (CSS) describe how HTML elements are displayed on screen.',
    xpReward: 10,
  ),
  QuizQuestion(
    id: 'q_lang_05',
    instruction: 'Which language is the standard for querying and manipulating relational databases?',
    codeSnippet: 'SELECT * FROM users WHERE age > 18;',
    correctAnswer: 'SQL',
    options: ['NoSQL', 'SQL', 'Python', 'Bash'],
    explanation: 'Structured Query Language (SQL) is used to communicate with relational databases.',
    xpReward: 10,
  ),
  QuizQuestion(
    id: 'q_lang_06',
    instruction: 'Which language was created by Apple specifically for iOS and macOS development?',
    codeSnippet: 'let message = "Hello, iOS"',
    correctAnswer: 'Swift',
    options: ['Objective-C', 'Swift', 'C#', 'Java'],
    explanation: 'Apple introduced Swift in 2014 as a safer, faster alternative to Objective-C.',
    xpReward: 10,
  ),
  QuizQuestion(
    id: 'q_lang_07',
    instruction: 'Which dynamic, open source programming language has a popular web framework named "Rails"?',
    codeSnippet: 'puts "Hello World"',
    correctAnswer: 'Ruby',
    options: ['Python', 'Ruby', 'PHP', 'Perl'],
    explanation: 'Ruby on Rails is one of the most famous web frameworks, built with the Ruby language.',
    xpReward: 10,
  ),
  QuizQuestion(
    id: 'q_lang_08',
    instruction: 'Which language powers the Flutter framework for building cross-platform apps?',
    codeSnippet: 'void main() => runApp(MyApp());',
    correctAnswer: 'Dart',
    options: ['Java', 'Dart', 'Kotlin', 'JavaScript'],
    explanation: 'Dart is the programming language used by Flutter to compile to native code across platforms.',
    xpReward: 10,
  ),
  QuizQuestion(
    id: 'q_lang_09',
    instruction: 'Which language was developed by Microsoft as part of its .NET initiative?',
    codeSnippet: 'Console.WriteLine("Hello World");',
    correctAnswer: 'C#',
    options: ['C++', 'F#', 'C#', 'Java'],
    explanation: 'C# is a modern, object-oriented language developed by Microsoft for the .NET ecosystem.',
    xpReward: 10,
  ),
  QuizQuestion(
    id: 'q_lang_10',
    instruction: 'Which language forms the structural foundation of the World Wide Web?',
    codeSnippet: '<div>Hello World</div>',
    correctAnswer: 'HTML',
    options: ['XML', 'HTML', 'JavaScript', 'CSS'],
    explanation: 'HyperText Markup Language (HTML) is the standard markup language for documents designed to be displayed in a web browser.',
    xpReward: 10,
  ),

  // Intermediate
  QuizQuestion(
    id: 'q_lang_11',
    instruction: 'Which language uses "Goroutines" for lightweight concurrency?',
    codeSnippet: 'go runThisTask()',
    correctAnswer: 'Go',
    options: ['Rust', 'Go', 'Erlang', 'Java'],
    explanation: 'Goroutines are functions or methods that run concurrently with other functions or methods in Go.',
    xpReward: 15,
  ),
  QuizQuestion(
    id: 'q_lang_12',
    instruction: 'Which language uses a "Borrow Checker" to ensure memory safety without garbage collection?',
    codeSnippet: 'let s1 = String::from("hello");\nlet s2 = s1;',
    correctAnswer: 'Rust',
    options: ['C++', 'Go', 'Rust', 'Swift'],
    explanation: 'Rust guarantees memory safety by utilizing an ownership system verified by the borrow checker at compile time.',
    xpReward: 15,
  ),
  QuizQuestion(
    id: 'q_lang_13',
    instruction: 'Which language distinguishes between loose equality (==) and strict equality (===)?',
    codeSnippet: 'if (0 == "0") // true\nif (0 === "0") // false',
    correctAnswer: 'JavaScript',
    options: ['PHP', 'JavaScript', 'Ruby', 'Python'],
    explanation: 'JavaScript uses === to check both value and type, while == performs type coercion before comparison.',
    xpReward: 15,
  ),
  QuizQuestion(
    id: 'q_lang_14',
    instruction: 'Which language is famously associated with the philosophy "Write Once, Run Anywhere"?',
    codeSnippet: 'public static void main(String[] args)',
    correctAnswer: 'Java',
    options: ['C#', 'Java', 'Python', 'C++'],
    explanation: 'Java was designed so that compiled Java code can run on all platforms that support Java without the need for recompilation (via the JVM).',
    xpReward: 15,
  ),
  QuizQuestion(
    id: 'q_lang_15',
    instruction: 'Which language is a strict syntactical superset of JavaScript that adds optional static typing?',
    codeSnippet: 'let isDone: boolean = false;',
    correctAnswer: 'TypeScript',
    options: ['TypeScript', 'CoffeeScript', 'Dart', 'Flow'],
    explanation: 'TypeScript adds optional static typing to JavaScript, helping to catch errors early through the type system.',
    xpReward: 15,
  ),
  QuizQuestion(
    id: 'q_lang_16',
    instruction: 'Which fundamental language relies heavily on pointers and manual memory management with malloc/free?',
    codeSnippet: 'int *ptr = (int*) malloc(sizeof(int));',
    correctAnswer: 'C',
    options: ['C++', 'Rust', 'C', 'Assembly'],
    explanation: 'C provides low-level access to memory through pointers and requires manual allocation and deallocation.',
    xpReward: 15,
  ),
  QuizQuestion(
    id: 'q_lang_17',
    instruction: 'Which language, widely used in web development, was originally created by Rasmus Lerdorf in 1994?',
    codeSnippet: '<?php echo "Hello World"; ?>',
    correctAnswer: 'PHP',
    options: ['Perl', 'PHP', 'Ruby', 'Python'],
    explanation: 'PHP (Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development.',
    xpReward: 15,
  ),
  QuizQuestion(
    id: 'q_lang_18',
    instruction: 'Which language is considered the standard scripting language for Unix-based operating systems?',
    codeSnippet: '#!/bin/bash\necho "Hello"',
    correctAnswer: 'Bash',
    options: ['Python', 'Perl', 'Bash', 'Lua'],
    explanation: 'Bash (Bourne Again SHell) is the default command-line interpreter for most Linux distributions and macOS.',
    xpReward: 15,
  ),
  QuizQuestion(
    id: 'q_lang_19',
    instruction: 'Which language is often used as a lightweight, embeddable scripting language in video games like World of Warcraft?',
    codeSnippet: 'print("Hello World")',
    correctAnswer: 'Lua',
    options: ['Python', 'Lua', 'Ruby', 'JavaScript'],
    explanation: 'Lua is a powerful, efficient, lightweight, embeddable scripting language commonly used in game engines.',
    xpReward: 15,
  ),
  QuizQuestion(
    id: 'q_lang_20',
    instruction: 'Which language was developed by Bjarne Stroustrup as an extension to C with object-oriented features?',
    codeSnippet: 'std::cout << "Hello" << std::endl;',
    correctAnswer: 'C++',
    options: ['C#', 'Java', 'C++', 'Objective-C'],
    explanation: 'C++ was originally known as "C with Classes" and was designed by Bjarne Stroustrup.',
    xpReward: 15,
  ),

  // Advanced
  QuizQuestion(
    id: 'q_lang_21',
    instruction: 'Which language powers the BEAM VM, commonly known for Elixir and high-concurrency systems?',
    codeSnippet: 'spawn(Function)',
    correctAnswer: 'Erlang',
    options: ['Haskell', 'Erlang', 'Clojure', 'Scala'],
    explanation: 'Erlang was built by Ericsson for telecom systems and runs on the BEAM VM, allowing massive concurrency.',
    xpReward: 20,
  ),
  QuizQuestion(
    id: 'q_lang_22',
    instruction: 'Which pure object-oriented language introduced the concept of sending "messages" to objects?',
    codeSnippet: 'Transcript show: \'Hello World\'.',
    correctAnswer: 'Smalltalk',
    options: ['Java', 'C++', 'Simula', 'Smalltalk'],
    explanation: 'Smalltalk is considered one of the most influential object-oriented programming languages, introducing message passing.',
    xpReward: 20,
  ),
  QuizQuestion(
    id: 'q_lang_23',
    instruction: 'Which language is specifically designed for writing smart contracts on the Ethereum blockchain?',
    codeSnippet: 'contract HelloWorld {\n    // ...\n}',
    correctAnswer: 'Solidity',
    options: ['Rust', 'Vyper', 'Solidity', 'Go'],
    explanation: 'Solidity is an object-oriented, high-level language for implementing smart contracts on Ethereum.',
    xpReward: 20,
  ),
  QuizQuestion(
    id: 'q_lang_24',
    instruction: 'Which language is known for its fully parenthesized prefix notation (S-expressions)?',
    codeSnippet: '(defun factorial (n)\n  (if (<= n 1)\n      1\n      (* n (factorial (- n 1)))))',
    correctAnswer: 'Lisp',
    options: ['Haskell', 'Lisp', 'Prolog', 'Forth'],
    explanation: 'Lisp (LISt Processing) uses S-expressions for both code and data, giving it its distinct parenthesized syntax.',
    xpReward: 20,
  ),
  QuizQuestion(
    id: 'q_lang_25',
    instruction: 'Which purely functional programming language explicitly uses "Monads" to handle side effects?',
    codeSnippet: 'main = putStrLn "Hello, World!"',
    correctAnswer: 'Haskell',
    options: ['OCaml', 'Elm', 'Haskell', 'F#'],
    explanation: 'Haskell is a purely functional programming language that uses monads (like the IO monad) to separate side effects from pure functions.',
    xpReward: 20,
  ),
  QuizQuestion(
    id: 'q_lang_26',
    instruction: 'Which modern functional language is heavily integrated with the Java Virtual Machine (JVM) and inspired by Lisp?',
    codeSnippet: '(println "Hello World")',
    correctAnswer: 'Clojure',
    options: ['Scala', 'Groovy', 'Clojure', 'Kotlin'],
    explanation: 'Clojure is a modern, dynamic, and functional dialect of the Lisp programming language on the Java platform.',
    xpReward: 20,
  ),
  QuizQuestion(
    id: 'q_lang_27',
    instruction: 'Which language was developed by the US Department of Defense and named after the world\'s first computer programmer?',
    codeSnippet: 'with Ada.Text_IO;\nprocedure Hello is...',
    correctAnswer: 'Ada',
    options: ['Cobol', 'Fortran', 'Pascal', 'Ada'],
    explanation: 'Ada was developed in the early 1980s for the DoD and was named after Ada Lovelace.',
    xpReward: 20,
  ),
  QuizQuestion(
    id: 'q_lang_28',
    instruction: 'Which functional language blends object-oriented and functional paradigms and runs on the JVM (often used with Apache Spark)?',
    codeSnippet: 'object Hello extends App {\n  println("Hello")\n}',
    correctAnswer: 'Scala',
    options: ['Kotlin', 'Scala', 'Clojure', 'Groovy'],
    explanation: 'Scala (Scalable Language) combines object-oriented and functional programming and is prominent in data engineering.',
    xpReward: 20,
  ),
  QuizQuestion(
    id: 'q_lang_29',
    instruction: 'Which language is functional, strongly typed, and native to the Microsoft .NET framework?',
    codeSnippet: 'let message = "Hello World"',
    correctAnswer: 'F#',
    options: ['C#', 'Visual Basic', 'F#', 'Haskell'],
    explanation: 'F# is a mature, open source, cross-platform functional-first programming language running on .NET.',
    xpReward: 20,
  ),
  QuizQuestion(
    id: 'q_lang_30',
    instruction: 'Which language uses a highly concurrent actor model and was explicitly built by José Valim to leverage the Erlang VM?',
    codeSnippet: 'defmodule Hello do\n  def world do\n    IO.puts "Hello"\n  end\nend',
    correctAnswer: 'Elixir',
    options: ['Erlang', 'Elixir', 'Crystal', 'Nim'],
    explanation: 'Elixir is a dynamic, functional language designed for building scalable and maintainable applications, running on the BEAM virtual machine.',
    xpReward: 20,
  ),
];
