// Copyright (c) 2026 TaskQuest. All rights reserved.

import 'package:taskquest/features/games/models/game_models.dart';

final List<SdlcSequence> allSdlcSequences = [
  SdlcSequence(
    id: 's_1',
    instruction: 'CI/CD Pipeline',
    explanation: 'Standard automated deployment pipeline.',
    correctOrder: ['Lint Code', 'Run Unit Tests', 'Build Image', 'Run E2E Tests', 'Deploy'],
    shuffledPhases: ['Run E2E Tests', 'Lint Code', 'Deploy', 'Run Unit Tests', 'Build Image'],
    xpReward: 20,
  ),
  SdlcSequence(
    id: 's_2',
    instruction: 'System Design',
    explanation: 'System design interview process.',
    correctOrder: ['Gather Requirements', 'API Design', 'Data Model', 'High-Level Design', 'Deep Dive'],
    shuffledPhases: ['API Design', 'Deep Dive', 'Gather Requirements', 'High-Level Design', 'Data Model'],
    xpReward: 20,
  ),
  SdlcSequence(
    id: 's_3',
    instruction: 'Incident Response',
    explanation: 'Standard incident handling.',
    correctOrder: ['Detect', 'Triage', 'Mitigate', 'Resolve', 'Post-Mortem'],
    shuffledPhases: ['Resolve', 'Triage', 'Detect', 'Post-Mortem', 'Mitigate'],
    xpReward: 20,
  ),
  SdlcSequence(
    id: 's_4',
    instruction: 'Pull Request',
    explanation: 'Standard code contribution workflow.',
    correctOrder: ['Branch', 'Commit', 'Push', 'Code Review', 'Merge'],
    shuffledPhases: ['Code Review', 'Commit', 'Merge', 'Branch', 'Push'],
    xpReward: 15,
  ),
  SdlcSequence(
    id: 's_5',
    instruction: 'Agile Sprint',
    explanation: 'Standard Scrum/Agile iteration.',
    correctOrder: ['Planning', 'Daily Standup', 'Development', 'Review', 'Retrospective'],
    shuffledPhases: ['Review', 'Daily Standup', 'Retrospective', 'Planning', 'Development'],
    xpReward: 15,
  ),
  SdlcSequence(
    id: 's_6',
    instruction: 'TDD',
    explanation: 'Test-Driven Development cycle.',
    correctOrder: ['Write Failing Test', 'Run Test (Fails)', 'Write Code', 'Run Test (Passes)', 'Refactor'],
    shuffledPhases: ['Write Code', 'Refactor', 'Run Test (Fails)', 'Write Failing Test', 'Run Test (Passes)'],
    xpReward: 20,
  ),
  SdlcSequence(
    id: 's_7',
    instruction: 'Machine Learning',
    explanation: 'ML model development lifecycle.',
    correctOrder: ['Data Collection', 'Data Preprocessing', 'Model Training', 'Model Evaluation', 'Deployment'],
    shuffledPhases: ['Model Training', 'Data Collection', 'Deployment', 'Data Preprocessing', 'Model Evaluation'],
    xpReward: 25,
  ),
  SdlcSequence(
    id: 's_8',
    instruction: 'UX Design',
    explanation: 'User experience design process.',
    correctOrder: ['User Research', 'Wireframing', 'Prototyping', 'User Testing', 'Visual Design'],
    shuffledPhases: ['User Testing', 'Visual Design', 'Wireframing', 'User Research', 'Prototyping'],
    xpReward: 15,
  ),
  SdlcSequence(
    id: 's_9',
    instruction: 'Security Audit',
    explanation: 'Standard security review process.',
    correctOrder: ['Threat Modeling', 'Static Analysis', 'Dynamic Analysis', 'Penetration Testing', 'Remediation'],
    shuffledPhases: ['Dynamic Analysis', 'Remediation', 'Threat Modeling', 'Penetration Testing', 'Static Analysis'],
    xpReward: 25,
  ),
  SdlcSequence(
    id: 's_10',
    instruction: 'Data Engineering',
    explanation: 'ETL Pipeline construction.',
    correctOrder: ['Data Extraction', 'Data Validation', 'Data Transformation', 'Data Loading', 'Data Analysis'],
    shuffledPhases: ['Data Transformation', 'Data Analysis', 'Data Extraction', 'Data Loading', 'Data Validation'],
    xpReward: 20,
  ),
  SdlcSequence(
    id: 's_11',
    instruction: 'DevOps Setup',
    explanation: 'Setting up a new project infrastructure.',
    correctOrder: ['Version Control Setup', 'Infrastructure as Code', 'CI/CD Configuration', 'Monitoring Setup', 'Alerting Setup'],
    shuffledPhases: ['Alerting Setup', 'Version Control Setup', 'Monitoring Setup', 'CI/CD Configuration', 'Infrastructure as Code'],
    xpReward: 25,
  ),
  SdlcSequence(
    id: 's_12',
    instruction: 'Bug Triage',
    explanation: 'Handling user-reported bugs.',
    correctOrder: ['Report Received', 'Reproduce Bug', 'Assess Severity', 'Assign to Developer', 'Schedule Fix'],
    shuffledPhases: ['Assess Severity', 'Report Received', 'Schedule Fix', 'Reproduce Bug', 'Assign to Developer'],
    xpReward: 15,
  ),
  SdlcSequence(
    id: 's_13',
    instruction: 'Release Management',
    explanation: 'Software release process.',
    correctOrder: ['Feature Freeze', 'Release Branch Creation', 'QA Sign-off', 'Production Deployment', 'Post-Release Monitoring'],
    shuffledPhases: ['Production Deployment', 'Feature Freeze', 'Post-Release Monitoring', 'QA Sign-off', 'Release Branch Creation'],
    xpReward: 20,
  ),
  SdlcSequence(
    id: 's_14',
    instruction: 'Database Migration',
    explanation: 'Safely altering database schemas.',
    correctOrder: ['Create Migration Script', 'Test on Staging', 'Backup Production DB', 'Apply Migration', 'Verify Data Integrity'],
    shuffledPhases: ['Backup Production DB', 'Create Migration Script', 'Verify Data Integrity', 'Apply Migration', 'Test on Staging'],
    xpReward: 25,
  ),
  SdlcSequence(
    id: 's_15',
    instruction: 'Cloud Migration',
    explanation: 'Moving on-premise to cloud.',
    correctOrder: ['Assessment', 'Planning', 'Pilot Migration', 'Data Migration', 'Cutover'],
    shuffledPhases: ['Data Migration', 'Assessment', 'Cutover', 'Planning', 'Pilot Migration'],
    xpReward: 25,
  ),
];
